//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Broker
{
    using System;
    using System.Collections.Generic;
    
    public partial class TELEFONO
    {
        public long ID { get; set; }
        public string TELEFONO1 { get; set; }
        public long IDCLIENTE { get; set; }
    
        public virtual CLIENTE CLIENTE { get; set; }
    }
}
